name: Animal Shelter Docker Compose (without nginx)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-compose:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ›  Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸš€ Start services (without nginx)
        run: docker-compose up -d redis-ansh zookeeper-ansh kafka-ansh postgres-animal-shelter postgres-animal-shelter-notification ansh-service ansh-notification-service ansh-react-app

      - name: ğŸ“œ Show all running containers
        run: docker ps -a

      - name: ğŸš€ Check if services are running
        run: |
          curl -k --retry 5 --retry-delay 5 http://localhost:8443 || (echo "ansh-service is not running" && exit 1)
          curl -k --retry 5 --retry-delay 5 http://localhost:8444 || (echo "ansh-notification-service is not running" && exit 1)

      - name: ğŸ›‘ Stop containers
        run: docker-compose down
